// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebAppTb01Lab1_Greselle.Models;

namespace WebAppTb01Lab1_Greselle.Migrations
{
    [DbContext(typeof(AutomovelContext))]
    [Migration("20180327014036_Banco2")]
    partial class Banco2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppTb01Lab1_Greselle.Models.Automovel", b =>
                {
                    b.Property<int>("AutomovelID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Datacadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<bool?>("Disponivel");

                    b.Property<string>("Marca")
                        .IsRequired();

                    b.Property<int>("Tipo");

                    b.HasKey("AutomovelID");

                    b.ToTable("Automovel");
                });
#pragma warning restore 612, 618
        }
    }
}
